import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import pluginQuery from "@tanstack/eslint-plugin-query";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // EVT-002. @tanstack/eslint-plugin-query was installed but never registered,
  // so none of its rules ever ran. TanStack Query owns all server state
  // (FRONTEND_ARCHITECTURE.md §5), which makes its correctness rules worth
  // enforcing rather than shipping unused.
  ...pluginQuery.configs["flat/recommended"],

  {
    rules: {
      // A dependency missing from a query key silently serves another
      // organization's cached data after a context switch. That is a
      // cross-tenant leak on the client, so it is an error, not a warning.
      "@tanstack/query/exhaustive-deps": "error",
    },
  },

  {
    // Generated by the shadcn CLI and regenerated wholesale: a fix here is
    // discarded by the next `shadcn add`. Linted loosely on purpose; the single
    // dangerouslySetInnerHTML it contains is budgeted in security.yml.
    files: ["src/components/ui/**"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Build and report output.
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
