import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

/**
 * Unit and component tests.
 *
 * Playwright owns end-to-end flows and is configured separately in
 * playwright.config.ts. The `exclude` below keeps the two runners from
 * collecting each other's files, which is the usual failure when both live in
 * the same repository.
 */
export default defineConfig({
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./vitest.setup.ts"],
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
    exclude: ["node_modules/**", ".next/**", "e2e/**"],
    coverage: {
      provider: "v8",
      reportsDirectory: "coverage",
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        // Generated by the shadcn CLI and regenerated wholesale: covering it
        // would measure someone else's code.
        "src/components/ui/**",
        "src/**/*.d.ts",
        "src/**/index.ts",
      ],
    },
  },
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
});
